name: Flutter CI with Android Emulator

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: macos-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Setup Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5'
          channel: 'stable'
          cache: true

      # Step 3: Setup Android Emulator
      - name: Setup Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 33
          target: google_apis
          arch: x86_64
          profile: Nexus 6
          script: |
            echo "Android Emulator is ready."
            flutter doctor
            flutter pub get
            flutter test

      # Step 4: Check ADB Devices
      - name: Check ADB Devices
        run: |
          echo "Checking if ADB devices are connected..."
          timeout=30  # Timeout in seconds
          elapsed_time=0
          while [[ -z "$(adb devices | grep 'device$')" ]] && [[ $elapsed_time -lt $timeout ]]; do
            echo "Waiting for emulator to show up in ADB devices... $elapsed_time seconds elapsed."
            sleep 5
            elapsed_time=$((elapsed_time + 5))
          done

          if [[ $elapsed_time -ge $timeout ]]; then
            echo "ADB devices check timed out after $timeout seconds."
            adb devices
            exit 1
          else
            echo "Emulator connected successfully in ADB devices."
          fi
        shell: bash

      # Step 5: Run Patrol Integration Tests
      - name: Run Patrol Tests
        run: |
          export PATH="$PATH":"$HOME/.pub-cache/bin"
          patrol test -t integration_test/app_test.dart --target-platform android
        shell: bash
